version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234556789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234556789
      - POSTGRES_DB=database
    ports:
      -  "5432"
    volumes:
      - "postgres_db:/var/lib/postgresql/data/"
volumes:
  postgres_db: